baseURL = "/"
languageCode = "en-us"
title = "Poetry Package Manager"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Poetry is a tool to manage dependencies and packages in python.You can manage, build, package, publish your project and also track the dependencies with Poetry.'
  homepage_image = '/images/poetry_terminal.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.logo]
      mobile = "https://python-poetry.org/images/logo-origami.svg"
      standard  = "https://python-poetry.org/images/logo-origami.svg"
